# 빌드 단계
FROM eclipse-temurin:21-jdk-alpine AS build

# 컨테이너 내부 작업 디렉토리 설정
WORKDIR /app

# 프로젝트 전체 파일 복사
COPY . ./

# gradlew 실행 권한 추가
RUN chmod +x gradlew

# 의존성 다운로드
RUN ./gradlew dependencies --no-daemon

# 프로젝트 빌드
RUN ./gradlew bootJar --no-daemon

# 실행 단계
FROM eclipse-temurin:21-jre-alpine

# 컨테이너 내부 작업 디렉토리 설정
WORKDIR /app

# 빌드 단계에서 생성된 JAR 파일 복사
COPY --from=build /app/build/libs/*.jar app.jar

# Spring Boot 프로젝트 포트 노출
EXPOSE 8080

# 프로젝트 실행 명령어
CMD ["java", "-jar", "app.jar"]