# 멀티 스테이지 빌드 미활용 dockerfile

# 빌드 & 실행
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# 프로젝트 빌드를 위한 Gradle 파일 복사
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle

# gradlew 실행 권한 추가
RUN chmod +x gradlew

# 의존성 다운로드
RUN ./gradlew dependencies --no-daemon

# 프로젝트 전체 파일 복사
COPY . ./

# 프로젝트 빌드
RUN ./gradlew bootJar --no-daemon

# Spring Boot 포트 명시
EXPOSE 8080

# 프로젝트 실행 명령어
CMD ["java", "-jar", "/app/build/libs/app.jar"]